export const INCREASE_TOTALXP = 'INCREASE_TOTALXP'
export const RESET_TOTALXP = 'RESET_TOTALXP'

export const INCREASE_LESSON = 'INCREASE_LESSON'
export const RESET_LESSON = 'RESET_LESSON'


export const INCREASE_QUESTION = 'INCREASE_QUESTION'
export const RESET_QUESTION = 'RESET_QUESTION'
export const RESET_MISTAKE = 'RESET_MISTAKE'
export const INCREASE_MISTAKE = 'INCREASE_MISTAKE'
export const RESET_CORRECT = 'RESET_CORRECT'
export const INCREASE_CORRECT = 'INCREASE_CORRECT'


export const SHOWMODAL_FALSE = 'SHOWMODAL_FALSE'